USE [master]
GO
/****** Object:  Database [Trading2022]    Script Date: 7/12/2023 8:30:06 PM ******/
CREATE DATABASE [Trading2022]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Trading2022', FILENAME = N'C:\Semter 4\PRJ301\FN project\ProjectPRJ\Trading2022.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Trading2022_log', FILENAME = N'C:\Semter 4\PRJ301\FN project\ProjectPRJ\Trading2022_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Trading2022] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Trading2022].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Trading2022] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Trading2022] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Trading2022] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Trading2022] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Trading2022] SET ARITHABORT OFF 
GO
ALTER DATABASE [Trading2022] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Trading2022] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Trading2022] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Trading2022] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Trading2022] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Trading2022] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Trading2022] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Trading2022] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Trading2022] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Trading2022] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Trading2022] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Trading2022] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Trading2022] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Trading2022] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Trading2022] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Trading2022] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Trading2022] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Trading2022] SET RECOVERY FULL 
GO
ALTER DATABASE [Trading2022] SET  MULTI_USER 
GO
ALTER DATABASE [Trading2022] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Trading2022] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Trading2022] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Trading2022] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Trading2022] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Trading2022] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Trading2022', N'ON'
GO
ALTER DATABASE [Trading2022] SET QUERY_STORE = OFF
GO
USE [Trading2022]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 7/12/2023 8:30:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[Username] [varchar](20) NOT NULL,
	[Password] [varchar](20) NULL,
	[role] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cart]    Script Date: 7/12/2023 8:30:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cart](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [varchar](50) NULL,
	[ProductName] [varchar](255) NULL,
	[ProductImage] [varchar](50) NULL,
	[Quantity] [int] NULL,
	[PriceProduct] [decimal](10, 2) NULL,
	[TotalPrice]  AS ([Quantity]*[PriceProduct]),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 7/12/2023 8:30:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[ID] [int] NOT NULL,
	[name] [nvarchar](30) NULL,
	[describe] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[products]    Script Date: 7/12/2023 8:30:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[ID] [varchar](10) NOT NULL,
	[name] [nvarchar](max) NULL,
	[quantity] [int] NULL,
	[price] [money] NULL,
	[releaseDate] [date] NULL,
	[describe] [nvarchar](max) NULL,
	[image] [nvarchar](max) NULL,
	[cid] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[products]  WITH CHECK ADD FOREIGN KEY([cid])
REFERENCES [dbo].[Categories] ([ID])
GO
USE [master]
GO
ALTER DATABASE [Trading2022] SET  READ_WRITE 
GO
